from app.models.patient import Patient
from app.models.doctor import Doctor
from app.models.admin import Admin
from app.models.doctor_document import DoctorDocument
from app.models.medical_record import MedicalRecord
from app.models.prescription import Prescription
from app.models.medicine import Medicine
from app.models.access_otp import AccessOTP
from app.models.notification import Notification